"""
===============================================================================
NeuroSense AI — Solution / Wellness Plan Report Generator
===============================================================================

Report Type:
    Personalized Wellness Plan / Solution Report

Purpose:
    Action-oriented safe support plan for the user.

Includes:
    - Top 5 suggestions
    - Daily practices
    - Grounding exercises
    - Sleep support
    - Social support plan
    - Professional help outside app
    - Crisis resources
    - Disclaimer

Safety:
    - No diagnosis
    - No medication advice
    - No psychiatrist impersonation
    - Refers to qualified professionals outside the app
===============================================================================
"""

import os
import csv
import html
import datetime
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

try:
    from utils.wellbeing_utils import (
        generate_safe_suggestions,
        summarize_checkin,
    )
except Exception:
    generate_safe_suggestions = None
    summarize_checkin = None

try:
    from utils.professional_help import (
        recommend_professional_help,
        format_resources_for_report,
        compact_professional_help_summary,
    )
except Exception:
    recommend_professional_help = None
    format_resources_for_report = None
    compact_professional_help_summary = None


# =============================================================================
# CONSTANTS
# =============================================================================

DISCLAIMER = (
    "This wellness plan is generated by NeuroSense AI for supportive self-care. "
    "It is not a diagnosis, medical treatment, psychiatric advice, or replacement "
    "for a licensed mental health professional. For urgent distress or safety risk, "
    "please contact emergency services or a crisis helpline."
)

CRISIS_RESOURCES = [
    "Tele MANAS: 14416 or 1800-891-4416",
    "iCALL: 9152987821 / icall@tiss.ac.in",
    "Vandrevala Foundation: +91 9999 666 555",
]

BLACK = colors.HexColor("#000000")
GREY = colors.HexColor("#555555")
LIGHT_BG = colors.HexColor("#F4F6FB")
BORDER = colors.HexColor("#D8DDEA")
SOFT_PRIMARY = colors.HexColor("#EEF2FF")
RED_BG = colors.HexColor("#FEF2F2")
RED = colors.HexColor("#B91C1C")


# =============================================================================
# STYLE HELPERS
# =============================================================================

def _styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="NS_Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=28,
        textColor=BLACK,
        alignment=TA_CENTER,
        spaceAfter=14,
    ))

    styles.add(ParagraphStyle(
        name="NS_Subtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=16,
        textColor=GREY,
        alignment=TA_CENTER,
        spaceAfter=18,
    ))

    styles.add(ParagraphStyle(
        name="NS_Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=20,
        textColor=BLACK,
        spaceBefore=14,
        spaceAfter=8,
    ))

    styles.add(ParagraphStyle(
        name="NS_Normal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=16,
        textColor=BLACK,
        alignment=TA_LEFT,
        spaceAfter=7,
    ))

    styles.add(ParagraphStyle(
        name="NS_Bold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=16,
        textColor=BLACK,
        spaceAfter=7,
    ))

    styles.add(ParagraphStyle(
        name="NS_Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=RED,
        backColor=RED_BG,
        borderColor=colors.HexColor("#FCA5A5"),
        borderWidth=1,
        borderPadding=8,
        spaceBefore=8,
        spaceAfter=12,
    ))

    return styles


def _safe(value: Any, default: str = "—") -> str:
    if value is None:
        return default

    text = str(value).strip()

    return text if text else default


def _shorten(value: Any, max_len: int = 90) -> str:
    text = _safe(value)

    if len(text) <= max_len:
        return text

    return text[: max_len - 3].rstrip() + "..."


def _section(story, styles, title: str):
    story.append(Paragraph(title, styles["NS_Section"]))


def _paragraph(story, styles, text: str):
    story.append(Paragraph(_escape_text(_safe(text)), styles["NS_Normal"]))


def _bullet_list(story, styles, items: List[str]):
    if not items:
        story.append(Paragraph("No data available.", styles["NS_Normal"]))
        return

    for item in items:
        story.append(Paragraph(f"• {_escape_text(_safe(item))}", styles["NS_Normal"]))


def _escape_text(value: Any) -> str:
    """
    Escape text for ReportLab Paragraph.
    Also preserves line breaks.
    """

    text = _safe(value)
    text = html.escape(text)
    text = text.replace("\n", "<br/>")
    return text


def _cell(value: Any, style):
    """
    Convert table cell text into ReportLab Paragraph so long text wraps properly.
    """

    return Paragraph(_escape_text(value), style)


def _table(data, col_widths=None):
    """
    ReportLab Table with Paragraph cells.

    This prevents overlapping text in PDF tables because Paragraph cells wrap
    within column width, while plain strings can overflow.
    """

    styles = _styles()

    cell_style = ParagraphStyle(
        name="NS_Table_Cell",
        parent=styles["NS_Normal"],
        fontName="Helvetica",
        fontSize=8.0,
        leading=10.5,
        textColor=BLACK,
        wordWrap="CJK",
        spaceAfter=0,
    )

    header_style = ParagraphStyle(
        name="NS_Table_Header",
        parent=styles["NS_Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.3,
        leading=10.5,
        textColor=BLACK,
        wordWrap="CJK",
        spaceAfter=0,
    )

    wrapped_data = []

    for row_index, row in enumerate(data):
        wrapped_row = []

        for cell in row:
            wrapped_row.append(
                _cell(
                    cell,
                    header_style if row_index == 0 else cell_style
                )
            )

        wrapped_data.append(wrapped_row)

    table = Table(
        wrapped_data,
        colWidths=col_widths,
        hAlign="LEFT",
        repeatRows=1,
        splitByRow=True,
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SOFT_PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), BLACK),
        ("TEXTCOLOR", (0, 1), (-1, -1), BLACK),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    return table


# =============================================================================
# DATA BUILDERS
# =============================================================================

def _latest_checkin(user_data: Dict[str, Any]) -> Dict[str, Any]:
    latest = user_data.get("latest_wellbeing_checkin")

    if latest:
        return latest

    checkins = user_data.get("wellbeing_checkins", []) or []

    if checkins:
        return checkins[-1]

    return {}


def _safe_suggestions(user_data: Dict[str, Any]) -> List[Dict[str, str]]:
    latest = _latest_checkin(user_data)

    if generate_safe_suggestions:
        try:
            suggestions = generate_safe_suggestions(latest, limit=5)

            if suggestions and isinstance(suggestions, list):
                return suggestions[:5]

        except Exception as e:
            print(f"⚠️ generate_safe_suggestions failed: {e}")

    return [
        {
            "title": "Box Breathing",
            "why": "Helps calm the body during stress.",
            "how_to_do": "Breathe in for 4 seconds, hold for 4, breathe out for 4, hold again for 4.",
            "frequency": "As needed",
            "category": "stress_regulation",
        },
        {
            "title": "Thought Journal",
            "why": "Helps organize difficult thoughts.",
            "how_to_do": "Write one difficult thought, one feeling, and one kinder alternative thought.",
            "frequency": "Daily",
            "category": "reflection",
        },
        {
            "title": "Sleep Wind-Down",
            "why": "Supports emotional recovery.",
            "how_to_do": "Avoid screens before bed and write tomorrow’s tasks.",
            "frequency": "Nightly",
            "category": "sleep",
        },
        {
            "title": "Trusted Person Check-In",
            "why": "Social support can reduce emotional isolation.",
            "how_to_do": "Send one short message to someone safe.",
            "frequency": "Today",
            "category": "social_support",
        },
        {
            "title": "5-4-3-2-1 Grounding",
            "why": "Helps bring attention back to the present moment.",
            "how_to_do": "Notice 5 things you see, 4 feel, 3 hear, 2 smell, and 1 taste.",
            "frequency": "Whenever overwhelmed",
            "category": "grounding",
        },
    ]


def _professional_help(user_data: Dict[str, Any]) -> Dict[str, Any]:
    latest = _latest_checkin(user_data)

    if recommend_professional_help:
        try:
            return recommend_professional_help(
                checkin=latest,
                message=latest.get("current_thoughts", ""),
                emotion=user_data.get("top_emotion", "neutral"),
                safety={},
            )
        except Exception as e:
            print(f"⚠️ recommend_professional_help failed: {e}")

    return {
        "needs_professional_help": False,
        "urgency": "none",
        "issue_tags": [],
        "recommendations": [],
        "resources": [],
        "user_facing_message": "",
        "disclaimer": DISCLAIMER,
    }


def _checkin_summary(user_data: Dict[str, Any]) -> Dict[str, Any]:
    latest = _latest_checkin(user_data)

    if summarize_checkin:
        try:
            return summarize_checkin(latest)
        except Exception as e:
            print(f"⚠️ summarize_checkin failed: {e}")

    if not latest:
        return {
            "available": False,
            "summary": "No wellbeing check-in is available yet.",
            "risk_level": "unknown",
            "wellbeing_score": None,
        }

    return {
        "available": True,
        "summary": "Latest wellbeing check-in is available.",
        "risk_level": latest.get("risk_level", "unknown"),
        "wellbeing_score": latest.get("wellbeing_score"),
    }


# =============================================================================
# PDF GENERATION
# =============================================================================

def generate_solution_pdf(user_data: Dict[str, Any], output_path: str) -> bool:
    """
    Generate Solution / Wellness Plan PDF.

    Required by generate_report.py:
        from generate_solution_report import generate_solution_pdf
    """

    styles = _styles()

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=0.40 * inch,
        leftMargin=0.40 * inch,
        topMargin=0.50 * inch,
        bottomMargin=0.50 * inch,
        title="NeuroSense AI Wellness Plan",
    )

    story = []

    report_date = user_data.get("report_date") or datetime.date.today().strftime("%d %B %Y")
    report_id = user_data.get("report_id") or f"NSP-{datetime.datetime.now().strftime('%Y%m%d%H%M')}"

    suggestions = _safe_suggestions(user_data)
    professional_help = _professional_help(user_data)
    checkin_summary = _checkin_summary(user_data)

    story.append(Paragraph("NeuroSense AI", styles["NS_Title"]))
    story.append(Paragraph("Personalized Wellness & Support Plan", styles["NS_Title"]))
    story.append(Paragraph(
        f"Report ID: {_escape_text(report_id)} &nbsp;&nbsp; | &nbsp;&nbsp; Generated: {_escape_text(report_date)}",
        styles["NS_Subtitle"],
    ))

    story.append(Paragraph(_escape_text(DISCLAIMER), styles["NS_Disclaimer"]))

    # -------------------------------------------------------------------------
    # 1. Current Support Summary
    # -------------------------------------------------------------------------

    _section(story, styles, "1. Current Support Summary")

    _paragraph(
        story,
        styles,
        checkin_summary.get("summary", "No wellbeing check-in is available yet.")
    )

    support_rows = [
        ["Field", "Value"],
        ["Wellbeing Score", _safe(checkin_summary.get("wellbeing_score"))],
        ["Risk / Support Need", _safe(checkin_summary.get("risk_level")).upper()],
        ["Dominant Emotion", _safe(user_data.get("top_emotion", "neutral")).capitalize()],
        ["Average Mood", f"{_safe(user_data.get('avg_mood'))}/10"],
    ]

    story.append(_table(
        support_rows,
        [2.1 * inch, 4.8 * inch],
    ))

    story.append(Spacer(1, 8))

    # -------------------------------------------------------------------------
    # 2. Top 5 Suggestions
    # -------------------------------------------------------------------------

    _section(story, styles, "2. Top 5 Personalized Suggestions")

    suggestion_rows = [["#", "Suggestion", "Why", "How To Do", "Frequency"]]

    for idx, item in enumerate(suggestions[:5], start=1):
        frequency = _shorten(item.get("frequency"), 28)

        suggestion_rows.append([
            str(idx),
            _shorten(item.get("title"), 34),
            _shorten(item.get("why") or item.get("description"), 125),
            _shorten(item.get("how_to_do") or item.get("description"), 150),
            frequency,
        ])

    story.append(_table(
        suggestion_rows,
        [
            0.32 * inch,   # #
            1.25 * inch,   # Suggestion
            1.75 * inch,   # Why
            2.45 * inch,   # How To Do
            1.10 * inch,   # Frequency
        ],
    ))

    story.append(Spacer(1, 8))

    # -------------------------------------------------------------------------
    # 3. Daily Practices
    # -------------------------------------------------------------------------

    _section(story, styles, "3. Daily Practices")

    daily_practices = [
        "Start the day with one 2-minute breathing exercise.",
        "Write one mood note: what happened, what I felt, what I need.",
        "Take one small action that supports your routine.",
        "Reduce screen exposure before sleep when possible.",
        "Check in with one trusted person if you feel isolated.",
    ]

    _bullet_list(story, styles, daily_practices)

    # -------------------------------------------------------------------------
    # 4. Grounding Exercises
    # -------------------------------------------------------------------------

    _section(story, styles, "4. Grounding & Emotional Regulation")

    grounding = [
        "5-4-3-2-1 grounding: notice 5 things you see, 4 you feel, 3 you hear, 2 you smell, and 1 you taste.",
        "Box breathing: breathe in for 4, hold for 4, breathe out for 4, hold for 4.",
        "Emotion naming: say, “I am noticing this feeling, and it makes sense because...”",
        "Small-step reset: choose one task that takes less than 5 minutes.",
    ]

    _bullet_list(story, styles, grounding)

    # -------------------------------------------------------------------------
    # 5. Sleep Support
    # -------------------------------------------------------------------------

    _section(story, styles, "5. Sleep & Recovery Support")

    sleep_support = [
        "Keep a consistent sleep and wake time when possible.",
        "Avoid heavy emotional problem-solving right before sleep.",
        "Write tomorrow’s tasks before bed to reduce mental load.",
        "Use a calm wind-down routine: dim lights, slow breathing, low stimulation.",
    ]

    _bullet_list(story, styles, sleep_support)

    # -------------------------------------------------------------------------
    # 6. Social Support
    # -------------------------------------------------------------------------

    _section(story, styles, "6. Social Support Plan")

    social_support = [
        "Identify one trusted person you can message or call.",
        "Use a simple message: “I’m having a difficult day. Can we talk for a few minutes?”",
        "If direct conversation feels hard, try text or voice note first.",
        "If you do not have support available, consider a counselling helpline.",
    ]

    _bullet_list(story, styles, social_support)

    # -------------------------------------------------------------------------
    # 7. Professional Help
    # -------------------------------------------------------------------------

    _section(story, styles, "7. Professional Help Outside NeuroSense AI")

    if compact_professional_help_summary:
        try:
            _paragraph(story, styles, compact_professional_help_summary(professional_help))
        except Exception:
            _paragraph(
                story,
                styles,
                professional_help.get(
                    "user_facing_message",
                    "Professional help can be considered if distress continues."
                )
            )
    else:
        _paragraph(
            story,
            styles,
            professional_help.get(
                "user_facing_message",
                "Professional help can be considered if distress continues."
            )
        )

    recommendations = professional_help.get("recommendations", []) or []

    if recommendations:
        rec_rows = [["Issue", "Suggested Professional", "Urgency", "Reason"]]

        for rec in recommendations:
            rec_rows.append([
                _shorten(rec.get("issue"), 40),
                _shorten(rec.get("professional"), 55),
                _shorten(rec.get("urgency"), 20),
                _shorten(rec.get("reason"), 150),
            ])

        story.append(_table(
            rec_rows,
            [
                1.1 * inch,
                1.65 * inch,
                0.9 * inch,
                3.2 * inch,
            ],
        ))
    else:
        _paragraph(
            story,
            styles,
            "No urgent professional referral signal was detected from available data. "
            "The user may still choose professional support if needed."
        )

    story.append(Spacer(1, 8))

    # -------------------------------------------------------------------------
    # 8. Resources
    # -------------------------------------------------------------------------

    _section(story, styles, "8. Verified Support Resources")

    resources = professional_help.get("resources", []) or []

    if format_resources_for_report and resources:
        try:
            resource_lines = format_resources_for_report(resources)
        except Exception:
            resource_lines = CRISIS_RESOURCES
    else:
        resource_lines = CRISIS_RESOURCES

    _bullet_list(story, styles, resource_lines)

    story.append(Paragraph(_escape_text(DISCLAIMER), styles["NS_Disclaimer"]))

    doc.build(story)

    return os.path.exists(output_path) and os.path.getsize(output_path) > 0


# =============================================================================
# CSV GENERATION
# =============================================================================

def generate_solution_csv(user_data: Dict[str, Any], output_path: str) -> bool:
    """
    Generate Solution / Wellness Plan CSV.

    Required by generate_report.py:
        from generate_solution_report import generate_solution_csv
    """

    suggestions = _safe_suggestions(user_data)
    professional_help = _professional_help(user_data)
    checkin_summary = _checkin_summary(user_data)

    rows = [
        ["Section", "Field", "Value"],
        ["Summary", "Name", user_data.get("name", "User")],
        ["Summary", "Wellbeing Score", checkin_summary.get("wellbeing_score", "—")],
        ["Summary", "Risk Level", checkin_summary.get("risk_level", "unknown")],
        ["Summary", "Dominant Emotion", user_data.get("top_emotion", "neutral")],
        ["Summary", "Disclaimer", DISCLAIMER],
    ]

    for idx, item in enumerate(suggestions[:5], start=1):
        rows.append([f"Top Suggestion {idx}", "Title", item.get("title", "")])
        rows.append([f"Top Suggestion {idx}", "Why", item.get("why") or item.get("description", "")])
        rows.append([f"Top Suggestion {idx}", "How To Do", item.get("how_to_do") or item.get("description", "")])
        rows.append([f"Top Suggestion {idx}", "Frequency", item.get("frequency", "")])

    rows.append(["Professional Help", "Needed", professional_help.get("needs_professional_help", False)])
    rows.append(["Professional Help", "Urgency", professional_help.get("urgency", "none")])
    rows.append(["Professional Help", "Message", professional_help.get("user_facing_message", "")])

    for rec in professional_help.get("recommendations", []) or []:
        rows.append(["Professional Recommendation", "Issue", rec.get("issue", "")])
        rows.append(["Professional Recommendation", "Professional", rec.get("professional", "")])
        rows.append(["Professional Recommendation", "Urgency", rec.get("urgency", "")])
        rows.append(["Professional Recommendation", "Reason", rec.get("reason", "")])

    for resource in professional_help.get("resources", []) or []:
        rows.append(["Resource", "Name", resource.get("name", "")])
        rows.append(["Resource", "Phone", resource.get("phone", "")])
        rows.append(["Resource", "Alternate Phone", resource.get("alternate_phone", "")])
        rows.append(["Resource", "WhatsApp", resource.get("whatsapp", "")])
        rows.append(["Resource", "Email", resource.get("email", "")])
        rows.append(["Resource", "Website", resource.get("website", "")])
        rows.append(["Resource", "Available", resource.get("available", "")])

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerows(rows)

    return os.path.exists(output_path) and os.path.getsize(output_path) > 0


# =============================================================================
# DIRECT TEST
# =============================================================================

if __name__ == "__main__":
    sample_user_data = {
        "name": "Prateek",
        "email": "test@example.com",
        "report_date": datetime.date.today().strftime("%d %B %Y"),
        "report_id": "NS-TEST",
        "top_emotion": "neutral",
        "avg_mood": 5.0,
        "wellbeing_checkins": [
            {
                "mood": "overwhelmed",
                "stress": 5,
                "social_connection": 2,
                "sleep": "poor",
                "concerns": ["academic_pressure", "loneliness"],
                "emotional_safety": 2,
                "support_available": "maybe",
                "current_thoughts": "I feel overloaded.",
                "wellbeing_score": 25,
                "risk_level": "high",
            }
        ],
        "latest_wellbeing_checkin": {
            "mood": "overwhelmed",
            "stress": 5,
            "social_connection": 2,
            "sleep": "poor",
            "concerns": ["academic_pressure", "loneliness"],
            "emotional_safety": 2,
            "support_available": "maybe",
            "current_thoughts": "I feel overloaded.",
            "wellbeing_score": 25,
            "risk_level": "high",
        },
    }

    generate_solution_pdf(sample_user_data, "test_solution_report.pdf")
    generate_solution_csv(sample_user_data, "test_solution_report.csv")

    print("Generated test_solution_report.pdf and test_solution_report.csv")