"""
===============================================================================
NeuroSense AI — Assessment Report Generator
===============================================================================

Report Type:
    Mental Wellness Assessment Report

Purpose:
    Observational report only.

Includes:
    - User session data
    - Detected emotions
    - Mood trend
    - Wellbeing check-in responses
    - Conversation history summary
    - Engagement patterns
    - Risk level
    - Limitations / disclaimer

Safety:
    - No diagnosis
    - No medication advice
    - No psychiatrist impersonation
    - No unsupported clinical claims
===============================================================================
"""

import os
import csv
import datetime
from collections import Counter
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)

try:
    from utils.wellbeing_utils import (
        summarize_checkin,
        summarize_wellbeing_trend,
    )
except Exception:
    summarize_checkin = None
    summarize_wellbeing_trend = None


# =============================================================================
# CONSTANTS
# =============================================================================

DISCLAIMER = (
    "This report is generated by NeuroSense AI for supportive wellness tracking. "
    "It is not a clinical diagnosis, medical report, psychiatric evaluation, or "
    "treatment plan. Please consult a qualified mental health professional for "
    "clinical assessment or treatment."
)

BLACK = colors.HexColor("#000000")
DARK = colors.HexColor("#111111")
GREY = colors.HexColor("#555555")
LIGHT_BG = colors.HexColor("#F4F6FB")
BORDER = colors.HexColor("#D8DDEA")
PRIMARY = colors.HexColor("#4F46E5")
SOFT_PRIMARY = colors.HexColor("#EEF2FF")
GREEN = colors.HexColor("#047857")
ORANGE = colors.HexColor("#C2410C")
RED = colors.HexColor("#B91C1C")


# =============================================================================
# STYLE HELPERS
# =============================================================================

def _styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="NS_Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=28,
        textColor=BLACK,
        alignment=TA_CENTER,
        spaceAfter=14,
    ))

    styles.add(ParagraphStyle(
        name="NS_Subtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=16,
        textColor=GREY,
        alignment=TA_CENTER,
        spaceAfter=18,
    ))

    styles.add(ParagraphStyle(
        name="NS_Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=20,
        textColor=BLACK,
        spaceBefore=14,
        spaceAfter=8,
    ))

    styles.add(ParagraphStyle(
        name="NS_Normal",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=16,
        textColor=BLACK,
        alignment=TA_LEFT,
        spaceAfter=7,
    ))

    styles.add(ParagraphStyle(
        name="NS_Bold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=16,
        textColor=BLACK,
        spaceAfter=7,
    ))

    styles.add(ParagraphStyle(
        name="NS_Small",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=GREY,
        spaceAfter=5,
    ))

    styles.add(ParagraphStyle(
        name="NS_Disclaimer",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=RED,
        backColor=colors.HexColor("#FEF2F2"),
        borderColor=colors.HexColor("#FCA5A5"),
        borderWidth=1,
        borderPadding=8,
        spaceBefore=8,
        spaceAfter=12,
    ))

    return styles


def _safe(value: Any, default: str = "—") -> str:
    if value is None:
        return default

    text = str(value).strip()

    return text if text else default


def _risk_color(risk: str):
    risk = (risk or "").lower()

    if risk == "high":
        return RED

    if risk == "medium":
        return ORANGE

    return GREEN


def _section(story, styles, title: str):
    story.append(Paragraph(title, styles["NS_Section"]))


def _paragraph(story, styles, text: str):
    story.append(Paragraph(_safe(text), styles["NS_Normal"]))


def _bullet_list(story, styles, items: List[str]):
    if not items:
        story.append(Paragraph("No data available.", styles["NS_Normal"]))
        return

    for item in items:
        story.append(Paragraph(f"• {_safe(item)}", styles["NS_Normal"]))


def _table(data, col_widths=None):
    table = Table(data, colWidths=col_widths, hAlign="LEFT")

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SOFT_PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), BLACK),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TEXTCOLOR", (0, 1), (-1, -1), BLACK),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.6, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))

    return table


# =============================================================================
# DATA BUILDERS
# =============================================================================

def _emotion_breakdown(user_data: Dict[str, Any]) -> List[List[str]]:
    emotion_freq = user_data.get("emotion_freq", {}) or {}

    if not emotion_freq:
        return [["Emotion", "Count", "Percentage"], ["No emotion data", "0", "0%"]]

    total = sum(emotion_freq.values()) or 1

    rows = [["Emotion", "Count", "Percentage"]]

    for emotion, count in sorted(
        emotion_freq.items(),
        key=lambda x: x[1],
        reverse=True,
    ):
        pct = round((count / total) * 100, 1)

        rows.append([
            emotion.capitalize(),
            str(count),
            f"{pct}%",
        ])

    return rows


def _latest_checkin_summary(user_data: Dict[str, Any]) -> Dict[str, Any]:
    latest = (
        user_data.get("latest_wellbeing_checkin")
        or (
            user_data.get("wellbeing_checkins", [])[-1]
            if user_data.get("wellbeing_checkins")
            else None
        )
    )

    if summarize_checkin:
        return summarize_checkin(latest)

    if not latest:
        return {
            "available": False,
            "summary": "No wellbeing check-in is available.",
            "wellbeing_score": None,
            "risk_level": "unknown",
        }

    return {
        "available": True,
        "summary": "A wellbeing check-in is available but detailed summarizer is unavailable.",
        "wellbeing_score": latest.get("wellbeing_score"),
        "risk_level": latest.get("risk_level", "unknown"),
    }


def _wellbeing_trend(user_data: Dict[str, Any]) -> Dict[str, Any]:
    checkins = user_data.get("wellbeing_checkins", []) or []

    if summarize_wellbeing_trend:
        return summarize_wellbeing_trend(checkins)

    if not checkins:
        return {
            "available": False,
            "trend": "limited_data",
            "summary": "No wellbeing check-ins are available.",
        }

    return {
        "available": True,
        "trend": "limited_data",
        "summary": f"{len(checkins)} wellbeing check-in(s) found.",
    }


def _conversation_summary(user_data: Dict[str, Any]) -> str:
    recent_sessions = user_data.get("recent_sessions", []) or []

    if not recent_sessions:
        return "No recent conversation history is available."

    user_messages = []

    for session in recent_sessions[:5]:
        for msg in session.get("messages", []):
            if msg.get("role") == "user":
                content = str(msg.get("content", "")).strip()

                if content:
                    user_messages.append(content[:180])

    if not user_messages:
        return "Recent sessions exist, but no user message content is available."

    sample = "; ".join(user_messages[:5])

    return (
        "Recent user messages indicate the following themes or concerns: "
        f"{sample}. This is an observational summary only."
    )


def _engagement_level(total_messages: int, total_sessions: int, streak: int) -> str:
    if total_messages >= 40 or total_sessions >= 8 or streak >= 7:
        return "High"

    if total_messages >= 10 or total_sessions >= 3 or streak >= 3:
        return "Moderate"

    return "Low"


# =============================================================================
# PDF GENERATION
# =============================================================================

def generate_assessment_pdf(user_data: Dict[str, Any], output_path: str) -> bool:
    """
    Generate Assessment Report PDF.
    """

    styles = _styles()

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
        title="NeuroSense AI Assessment Report",
    )

    story = []

    report_date = user_data.get("report_date") or datetime.date.today().strftime("%d %B %Y")
    report_id = user_data.get("report_id") or f"NSA-{datetime.datetime.now().strftime('%Y%m%d%H%M')}"

    story.append(Paragraph("NeuroSense AI", styles["NS_Title"]))
    story.append(Paragraph("Mental Wellness Assessment Report", styles["NS_Title"]))
    story.append(Paragraph(
        f"Report ID: {report_id} &nbsp;&nbsp; | &nbsp;&nbsp; Generated: {report_date}",
        styles["NS_Subtitle"],
    ))

    story.append(Paragraph(DISCLAIMER, styles["NS_Disclaimer"]))

    # -------------------------------------------------------------------------
    # User Overview
    # -------------------------------------------------------------------------

    _section(story, styles, "1. User & Session Overview")

    total_messages = int(user_data.get("total_messages", 0) or 0)
    total_sessions = int(user_data.get("total_sessions", 0) or 0)
    streak = int(user_data.get("streak", 0) or 0)
    avg_mood = user_data.get("avg_mood", "—")
    top_emotion = user_data.get("top_emotion", "neutral")

    overview_rows = [
        ["Field", "Value"],
        ["Name", _safe(user_data.get("name", "User"))],
        ["Email", _safe(user_data.get("email"))],
        ["Language", _safe(user_data.get("lang"))],
        ["Total Sessions", str(total_sessions)],
        ["Total Messages", str(total_messages)],
        ["Engagement Streak", f"{streak} day(s)"],
        ["Average Mood Score", f"{avg_mood}/10"],
        ["Dominant Detected Emotion", _safe(top_emotion).capitalize()],
        ["Engagement Level", _engagement_level(total_messages, total_sessions, streak)],
    ]

    story.append(_table(overview_rows, [2.2 * inch, 4.7 * inch]))

    # -------------------------------------------------------------------------
    # Emotion Analysis
    # -------------------------------------------------------------------------

    _section(story, styles, "2. Detected Emotion Patterns")

    story.append(_table(_emotion_breakdown(user_data), [2.3 * inch, 1.5 * inch, 2.1 * inch]))

    emotion_summary = (
        f"The most frequently detected emotion is {_safe(top_emotion).capitalize()}. "
        "This pattern is based on available emotion detection logs and should be treated "
        "as supportive context, not a diagnosis."
    )

    _paragraph(story, styles, emotion_summary)

    # -------------------------------------------------------------------------
    # Mood Trend
    # -------------------------------------------------------------------------

    _section(story, styles, "3. Mood Trend")

    mood_timeline = user_data.get("mood_timeline", []) or []
    daily_labels = user_data.get("daily_labels", []) or []

    mood_rows = [["Date", "Mood Score"]]

    if mood_timeline and daily_labels:
        for label, score in zip(daily_labels, mood_timeline):
            mood_rows.append([label, _safe(score, "No data")])
    else:
        mood_rows.append(["No data", "No data"])

    story.append(_table(mood_rows, [2.2 * inch, 2.2 * inch]))

    valid_mood = [x for x in mood_timeline if x is not None]

    if len(valid_mood) >= 2:
        if valid_mood[-1] > valid_mood[0]:
            trend = "improving"
        elif valid_mood[-1] < valid_mood[0]:
            trend = "declining"
        else:
            trend = "stable"
    else:
        trend = "limited data"

    _paragraph(
        story,
        styles,
        f"The observed mood trend is {trend}. This is calculated from available emotion-based mood scores only.",
    )

    # -------------------------------------------------------------------------
    # Wellbeing Check-in
    # -------------------------------------------------------------------------

    _section(story, styles, "4. Mental & Social Wellbeing Check-In")

    checkin_summary = _latest_checkin_summary(user_data)
    trend_summary = _wellbeing_trend(user_data)

    latest_score = checkin_summary.get("wellbeing_score", "—")
    risk_level = checkin_summary.get("risk_level", "unknown")

    checkin_rows = [
        ["Field", "Value"],
        ["Latest Wellbeing Score", _safe(latest_score)],
        ["Risk / Support Need Level", _safe(risk_level).upper()],
        ["Trend", _safe(trend_summary.get("trend", "limited_data"))],
        ["Check-in Summary", _safe(checkin_summary.get("summary"))],
    ]

    story.append(_table(checkin_rows, [2.2 * inch, 4.7 * inch]))

    _paragraph(story, styles, _safe(trend_summary.get("summary")))

    # -------------------------------------------------------------------------
    # Conversation History Summary
    # -------------------------------------------------------------------------

    _section(story, styles, "5. Conversation History Summary")

    _paragraph(story, styles, _conversation_summary(user_data))

    # -------------------------------------------------------------------------
    # Engagement Patterns
    # -------------------------------------------------------------------------

    _section(story, styles, "6. Engagement Patterns")

    daily_labels = user_data.get("daily_labels", []) or []
    daily_counts = user_data.get("daily_counts", []) or []

    engagement_rows = [["Date", "Messages"]]

    if daily_labels and daily_counts:
        for label, count in zip(daily_labels, daily_counts):
            engagement_rows.append([label, str(count)])
    else:
        engagement_rows.append(["No data", "0"])

    story.append(_table(engagement_rows, [2.2 * inch, 2.2 * inch]))

    engagement_summary = (
        f"The user's engagement level is {_engagement_level(total_messages, total_sessions, streak)} "
        f"based on {total_sessions} session(s), {total_messages} message(s), and a {streak}-day streak."
    )

    _paragraph(story, styles, engagement_summary)

    # -------------------------------------------------------------------------
    # Risk / Limitations
    # -------------------------------------------------------------------------

    _section(story, styles, "7. Risk Level & Limitations")

    risk_text = (
        f"Current support-need risk level: {risk_level}. "
        "This risk level is based on the wellbeing check-in and available interaction data. "
        "It is not a clinical risk assessment."
    )

    story.append(Paragraph(risk_text, styles["NS_Bold"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(DISCLAIMER, styles["NS_Disclaimer"]))

    doc.build(story)

    return os.path.exists(output_path) and os.path.getsize(output_path) > 0


# =============================================================================
# CSV GENERATION
# =============================================================================

def generate_assessment_csv(user_data: Dict[str, Any], output_path: str) -> bool:
    """
    Generate Assessment Report CSV.
    """

    checkin_summary = _latest_checkin_summary(user_data)
    trend_summary = _wellbeing_trend(user_data)

    rows = [
        ["Section", "Metric", "Value"],
        ["User", "Name", user_data.get("name", "User")],
        ["User", "Email", user_data.get("email", "—")],
        ["User", "Language", user_data.get("lang", "EN")],
        ["Session", "Total Sessions", user_data.get("total_sessions", 0)],
        ["Session", "Total Messages", user_data.get("total_messages", 0)],
        ["Session", "Streak", user_data.get("streak", 0)],
        ["Emotion", "Dominant Emotion", user_data.get("top_emotion", "neutral")],
        ["Mood", "Average Mood", user_data.get("avg_mood", "—")],
        ["Wellbeing", "Latest Score", checkin_summary.get("wellbeing_score", "—")],
        ["Wellbeing", "Risk Level", checkin_summary.get("risk_level", "unknown")],
        ["Wellbeing", "Trend", trend_summary.get("trend", "limited_data")],
        ["Wellbeing", "Summary", checkin_summary.get("summary", "No data")],
        ["Conversation", "Summary", _conversation_summary(user_data)],
        ["Disclaimer", "Safety", DISCLAIMER],
    ]

    emotion_freq = user_data.get("emotion_freq", {}) or {}

    for emotion, count in emotion_freq.items():
        rows.append(["Emotion Breakdown", emotion, count])

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerows(rows)

    return os.path.exists(output_path) and os.path.getsize(output_path) > 0